export const ADD_DATA = 'ADD_DATA'
export const DELETE_DATA = 'DELETE_DATA'
export const UPDATE_DATA = 'UPDATE_DATA'

export const LOAD_DATA = 'LOAD_DATA'
export const LOAD_PHONEBOOKS_FAILURE = 'LOAD_PHONEBOOKS_FAILURE'
export const LOAD_PHONEBOOKS_SUCCESS = 'LOAD_PHONEBOOKS_SUCCESS'


export const ADD_PHONEBOOK_SUCCESS = 'LOAD_PHONEBOOKS_FAILURE'
export const ADD_PHONEBOOK_FAILURE = 'ADD_PHONEBOOK_FAILURE'
